### ISSUE TITLE
Vertical and horizontal lines between tiles

### ISSUE THREAD

**Issue by stumpdk** [alfarisi/leaflet-deepzoom#1]
Thank you for a VERY useful plugin for Leaflet!
I'm using it in a cultural project in which we display old maps and drawings.
In some cases, there are one pixel of space between tiles, showing as vertical and horizontal lines dividing the images.
An example can be seen here: http://www.politietsregisterblade.dk/kildeviser/version3/#?collection=3&item=2479
The tiles are created using MapTiler, default settings.

**Comment by stumpdk** [comment]
The issue is experienced using Google Chrome v. 37.
The problem is not present when using Internet Explorer 10.

**Comment by alfarisi** [comment]
Have you tried it using Chrome 38?
